version: '3.8'

services:
  strapi:
    image: strapi/strapi
    container_name: strapi
    restart: always
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_NAME: strapi
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
    volumes:
      - ./strapi:/srv/app
      - ./strapi/data:/srv/app/data
    ports:
      - "1337:1337"
    networks:
      - my-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: strapi
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - my-network
    ports:
      - "3306:3306"

  nextjs:
    build: ./nextjs
    container_name: nextjs
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: http://strapi:1337
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - strapi

networks:
  my-network:
    driver: bridge